// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Work = Collections['works']['schema']['_output']
export declare const works: Work[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Chapter = Collections['chapters']['schema']['_output']
export declare const chapters: Chapter[]

export type Example = Collections['examples']['schema']['_output']
export declare const examples: Example[]
